trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master

variables:
  - name: buildConfiguration
    value: Release
  - template: ./azure-pipelines-variables-common.yml

stages:
- template: ./azure-pipelines-template.yml
  parameters:
    buildConfiguration: ${{ variables.buildConfiguration }}
    integrationTestSdkVersions: ${{ variables.integrationTestSdkVersions }}
    publish: false
