trigger:
  branches:
    include:
      - release/*
      - preview/*

variables:
  - name: buildConfiguration
    value: Release
  - template: ./lib/server/azure-pipelines-variables-common.yml
  - group: vs-marketplace-publisher

stages:
- template: ./azure-pipelines-template.yml
  parameters:
    buildConfiguration: ${{ variables.buildConfiguration }}
    integrationTestSdkVersions: ${{ variables.integrationTestSdkVersions }}
    publish: true
    vsMarketplacePublisherToken: $(VSMarketPlacePublisherToken)
